# Source directory
SRC=./src

# Variables for the lexer
LEXER=flex
LEXER_INFILE=$(SRC)/lex.l
LEXER_OUTFILE=lex_output.c
LEXER_OPTS=-d -o $(LEXER_OUTFILE)

# Variables for the parser
PARSER=yacc
PARSER_INFILE=$(SRC)/grammar.y
PARSER_OUTPREFIX=parser_output
PARSER_CFILE=$(PARSER_OUTPREFIX).c
PARSER_HFILE=$(PARSER_OUTPREFIX).h
PARSER_OPTS=-d -o $(PARSER_CFILE)

# Variables for the compiler
COMPILER=gcc
COMPILER_INFILES=$(PARSER_CFILE) $(LEXER_OUTFILE)
COMPILER_OUTFILE=compiler
COMPILER_OPTS=-o $(COMPILER_OUTFILE)




all: compile

compile: lex parse
	$(COMPILER) $(COMPILER_OPTS) $(COMPILER_INFILES)

lex: $(LEXER_INFILE)
	$(LEXER) $(LEXER_OPTS) $(LEXER_INFILE)

parse: $(PARSER_INFILE)
	$(PARSER) $(PARSER_OPTS) $(PARSER_INFILE)

clean:
	rm -f $(COMPILER_INFILES) $(COMPILER_OUTFILE) $(PARSER_CFILE) $(PARSER_HFILE)
